name: carousel_slider_for_hero_widget
description: A carousel slider widget, support infinite scroll and custom child widget.
version: 4.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
